{"success": true, "data": [{"type": "correct", "user": {"id": 843, "name": "Extrinsic"}, "challenge_id": 54, "date": "2024-04-26T15:44:56.726911+00:00", "id": 1213, "challenge": {"id": 54, "name": "sanitycheck", "value": 1, "category": "misc"}, "team": {"id": 499, "name": "GoodLuckHaveFun"}}], "meta": {"count": 1}}
